apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitconsumer
spec:
  selector:
    matchLabels:
      app: rabbitconsumer
  template:
    metadata:
      labels:
        app: rabbitconsumer
    spec:
      containers:
      - name: rabbitconsumer
        image: joohong89/assessment-consumer
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitconsumer
spec:
  type: NodePort
  selector:
    app: rabbitconsumer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31600


